using UnityEngine;
using System.Collections;

/// <summary>
/// Defines an interface for objects that can generate a group of cells.
/// </summary>
/// <seealso cref="Cell"/>
/// <seealso cref="CellGroup"/>
public interface ICellGenerator
{
    /// <summary>
    /// Gets the groups of cells that have been generated by this generator.
    /// </summary>
    CellGroup[] generatedGroups { get; }

    /// <summary>
    /// Generates a group of cells on demand.
    /// </summary>
    /// <returns>Returns a <see cref="CellGroup"/> object that represents the logical grouping of the cells.</returns>
    CellGroup GenerateCells();
}
