using UnityEngine;
using System.Collections;

/// <summary>
/// Defines a <see cref="ICellGenerator"/> that is able to generate groups of cells in the shape of a table.
/// </summary>
public class TableCellGenerator : MonoBehaviour, ICellGenerator
{
    /// <summary>
    /// Whether the table of cells should be generated when the Start() is called.
    /// </summary>
    public bool generateOnStart = false;
    
    /// <summary>
    /// The size that the table should be. (x, y)
    /// </summary>
    public Vector2 size = new Vector2(10, 10);

    /// <summary>
    /// Gets the groups of cells that have been generated by this generator.
    /// </summary>
    public CellGroup[] generatedGroups { get; private set; }

    /// <summary>
    /// Generates a group of cells on demand.
    /// </summary>
    /// <returns>Returns a <see cref="CellGroup"/> object that represents the logical grouping of the cells.</returns>
    public CellGroup GenerateCells()
    {
        Cell[] cells = new Cell[(int)(size.x * size.y)];

    }
}
